### ISSUE TITLE
Jekyll is making two secondary navs

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/portfolio#1]
In the parallax.html, the nav from projects.html in the _layouts folder is appearing twice. If I remove {{content}} from the parallax.html the secondary nav appears outside of the the main on the page.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Try deleting `{{content}}` from `parallax.html`—the `{{content}}` placeholder should only be used inside layouts.

**Comment by hldouglas** [comment]
I did, but then the second nav isn't inside the main any more. Is that something I'm just going to have to live with?

**Comment by thomasjbradley** [comment]
I don't think the `<nav>` needs to be inside the `<main>` at all. The navigation isn't *the* reason people come to *this* page, it only helps them get to *other* pages.

**Comment by hldouglas** [comment]
Okay. Thank you.
