### ISSUE TITLE
Positioning images in the embed container

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/portfolio#2]
I'm attempting to have certain embed containers be a different positioning at different sizes. Either they don't work or, the image doesn't reposition (as seen in the isometric.html).

    <div class="unit unit-xs-hidden unit-s-hidden unit-m-hidden unit-l-1-3 unit-xl-1-3">
      <figure>
        <div class="embed embed-1by1">
          <img itemprop="image" class="island-1-8 embed-item" src="{{site.baseurl}}/images/iso-sketch-2.jpg" alt="An isometric sketch of an IKEA showroom layout">
        </div>
        <figcaption class="gutter-1-2 micro">Another alternate early idea of an IKEA showroom</figcaption>
      </figure>
    </div>
    <div class="unit unit-xs-1 unit-s-1 unit-m-1-2 unit-l-hidden unit-xl-hidden">
      <figure>
        <div class="embed embed-185by100">
          <img itemprop="image" class="island-1-8 embed-item pin-c" src="{{site.baseurl}}/images/iso-sketch-2.jpg" alt="An isometric sketch of an IKEA showroom layout">
        </div>
        <figcaption class="gutter-1-2 micro">Another alternate early idea of an IKEA showroom</figcaption>
      </figure>
    </div>

    <div class="unit unit-xs-hidden unit-s-hidden unit-m-hidden unit-l-1-3 unit-xl-1-3">
      <figure>
        <div class="embed embed-1by1">
          <img itemprop="image" class="island-1-8 embed-item" src="{{site.baseurl}}/images/iso-sketch-3.jpg" alt="Personal comments with my sketches to consider when laying out the content">
        </div>
        <figcaption class="gutter-1-2 micro">Notes before creation</figcaption>
      </figure>
    </div>
    <div class="unit unit-xs-1 unit-s-1 unit-m-1 unit-l-hidden unit-xl-hidden">
      <figure>
        <div class="embed embed-185by100">
          <img itemprop="image" class="island-1-8 embed-item pin-bc" src="{{site.baseurl}}/images/iso-sketch-3.jpg" alt="Personal comments with my sketches to consider when laying out the content">
        </div>
        <figcaption class="gutter-1-2 micro">Notes before creation</figcaption>
      </figure>
    </div>

@thomasjbradley

**Comment by thomasjbradley** [comment]
The image inside the embed container isn't the same aspect ratio as the container itself?

**Comment by hldouglas** [comment]
The image inside the embed container is 1 by 1 and is the same as the embed container at screen sizes large and extra large. And then at smaller screens they're embedded as 185 by 100, but the images are still 1 by 1.

**Comment by thomasjbradley** [comment]
Okay. You could probably use `transform: translate()` to move the image around a little on the different screen sizes.
