### ISSUE TITLE
Running Jekyll

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/portfolio#3]
<img width="682" alt="screen shot 2019-01-22 at 14 01 54" src="https://user-images.githubusercontent.com/10465399/51558781-51ca3700-1e4e-11e9-96e0-a0ebaff73c2b.png">
Running into an issue running Jekyll. How do I "enable incremental?" I've already run an update.
@thomasjbradley

**Comment by thomasjbradley** [comment]
It looks like Terminal is opened to the wrong location. Did you press “Open in Terminal” from the GitHub Desktop application?

**Comment by hldouglas** [comment]
I've fixed it. There were several terminals open by accident. Thanks anyway Thomas.
